#!/bin/bash
code_dir="test/testFiles/code_generator_programs"
for file in `ls $code_dir`
do
    execname=${file%.bpl}
    ./bpl ${code_dir}/${file} > asm/${execname}.s
    gcc -g -o bin/${execname} asm/${execname}.s
done
